CREATE TABLE "Case" (caseID varchar(255) NOT NULL, DepartmentdepartmentID int4 NOT NULL, CitizenregardingCitizenID int4 NOT NULL, PRIMARY KEY (caseID));
CREATE TABLE Case_Content (caseContentID SERIAL NOT NULL, CasecaseID varchar(255) NOT NULL, dateStamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (caseContentID));
CREATE TABLE Case_Employee (CasecaseID varchar(255) NOT NULL, EmployeeemployeeID int4 NOT NULL, dateStamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (CasecaseID, EmployeeemployeeID));
CREATE TABLE Case_RequestingCitizen (CasecaseID varchar(255) NOT NULL, CitizenrequestingCitizenID int4 NOT NULL, PRIMARY KEY (CasecaseID, CitizenrequestingCitizenID));
CREATE TABLE Citizen (citizenID SERIAL NOT NULL, Zipcodezipcode int4 NOT NULL, firstName varchar(255) NOT NULL, lastName varchar(255) NOT NULL, "CPR-nr" varchar(255) NOT NULL, streetName varchar(255), houseNo varchar(255), floor varchar(255), floorDirection varchar(255), regardingCitizen bool NOT NULL, requestingCitizen bool NOT NULL, PRIMARY KEY (citizenID));
CREATE TABLE Department (departmentID SERIAL NOT NULL, departmentName varchar(255) NOT NULL, PRIMARY KEY (departmentID));
CREATE TABLE Employee (employeeID SERIAL NOT NULL, DepartmentdepartmentID int4 NOT NULL, RoleroleID int4 NOT NULL, firstName varchar(255) NOT NULL, lastName varchar(255) NOT NULL, username varchar(255) NOT NULL UNIQUE, password varchar(255) NOT NULL, PRIMARY KEY (employeeID));
CREATE TABLE Rights (rightsID SERIAL NOT NULL, rightsName varchar(225) NOT NULL, description text, PRIMARY KEY (rightsID));
CREATE TABLE Role (roleID SERIAL NOT NULL, roleName varchar(255) NOT NULL, PRIMARY KEY (roleID));
CREATE TABLE Role_Rights (RightsrightsID int4 NOT NULL, RoleroleID int4 NOT NULL, PRIMARY KEY (RightsrightsID, RoleroleID));
CREATE TABLE Zipcode (zipcode SERIAL NOT NULL, cityName varchar(255) NOT NULL, PRIMARY KEY (zipcode));
CREATE INDEX Citizen_firstName ON Citizen (firstName);
CREATE INDEX Citizen_lastName ON Citizen (lastName);
CREATE INDEX "Citizen_CPR-nr" ON Citizen ("CPR-nr");
ALTER TABLE Employee ADD CONSTRAINT FKEmployee169042 FOREIGN KEY (DepartmentdepartmentID) REFERENCES Department (departmentID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee127276 FOREIGN KEY (RoleroleID) REFERENCES Role (roleID);
ALTER TABLE Role_Rights ADD CONSTRAINT FKRole_Right154863 FOREIGN KEY (RightsrightsID) REFERENCES Rights (rightsID);
ALTER TABLE Role_Rights ADD CONSTRAINT FKRole_Right562123 FOREIGN KEY (RoleroleID) REFERENCES Role (roleID);
ALTER TABLE "Case" ADD CONSTRAINT FKCase853075 FOREIGN KEY (DepartmentdepartmentID) REFERENCES Department (departmentID);
ALTER TABLE Citizen ADD CONSTRAINT FKCitizen252567 FOREIGN KEY (Zipcodezipcode) REFERENCES Zipcode (zipcode);
ALTER TABLE Case_Employee ADD CONSTRAINT FKCase_Emplo114012 FOREIGN KEY (CasecaseID) REFERENCES "Case" (caseID);
ALTER TABLE Case_Employee ADD CONSTRAINT FKCase_Emplo731126 FOREIGN KEY (EmployeeemployeeID) REFERENCES Employee (employeeID);
ALTER TABLE "Case" ADD CONSTRAINT FKCase736884 FOREIGN KEY (CitizenregardingCitizenID) REFERENCES Citizen (citizenID);
ALTER TABLE Case_RequestingCitizen ADD CONSTRAINT FKCase_Reque2853 FOREIGN KEY (CasecaseID) REFERENCES "Case" (caseID);
ALTER TABLE Case_RequestingCitizen ADD CONSTRAINT FKCase_Reque839262 FOREIGN KEY (CitizenrequestingCitizenID) REFERENCES Citizen (citizenID);
ALTER TABLE Case_Content ADD CONSTRAINT FKCase_Conte796834 FOREIGN KEY (CasecaseID) REFERENCES "Case" (caseID);
